services:
  fireblocks-xrp-sdk:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./.env:/app/.env:ro
    ports:
      - "3000:3000"
    env_file: ./.env
    restart: unless-stopped
